services:
  traefik:
    image: "traefik:v3.0"
    container_name: "traefik"
    ports:
      - "80:80" # Mapowanie portu 80 hosta na port 80 kontenera
      - "443:443" # Mapowanie portu 443 hosta na port 443 kontenera
    command:
      - "--api.insecure=true" # Udostępnianie dashboardu bez uwierzytelniania
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      - "--entrypoints.web.address=:80" # Nasłuchiwanie na porcie 80 hosta
      - "--entrypoints.websecure.address=:443" # Nasłuchiwanie na porcie 443 hosta

      #DNS CHALLENGE
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=duckdns"
      - "--certificatesresolvers.letsencrypt.acme.email=tu_byl_moj@email.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      
    
    volumes:
      - "./letsencrypt:/letsencrypt" # Wolumen na przechowywanie certyfikatów
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

    environment:
      DUCKDNS_TOKEN: MOJ_TOKEN_DNS
      
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.api.service=api@internal"

networks:
  proxy:
    name: proxy
    external: true
